apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: 3x-ui-exporter
build:
  artifacts:
    - image: ghcr.io/br3d/3x-ui-exporter
      docker:
        buildArgs:
          ARCH: amd64
deploy:
  kustomize:
    paths:
      - k8s
