apiVersion: apps/v1
kind: Deployment
metadata:
  name: 3xui-exporter
spec:
  selector:
    matchLabels: {} # Managed by Kustomize
  template:
    metadata:
      labels: {} # Managed by Kustomize
    spec:
      containers:
        - name: 3xui-exporter
          image: ghcr.io/br3d/3x-ui-exporter
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          ports:
            - name: metrics
              containerPort: 9550
